const genre = [
  "Alternativ Death",
  "Alternative Metal",
  "Ambiant Black",
  "Atmospheric Black",
  "Atmospheric Death",
  "Atmospheric Doom",
  "Atmospheric Gothic",
  "Atmospheric Metal",
  "Atmospheric Sludge",
  "Avantgardiste Black",
  "Bay Area Thrash",
  "Black Dark",
  "Black Death",
  "Black Electro",
  "Black Heavy",
  "Black Metal",
  "Brutal Black",
  "Brutal Death",
  "Brutal Death Black",
  "Crossover",
  "Crust",
  "Cyber Metal",
  "Dark Ambient",
  "Dark Metal",
  "Death Black",
  "Death Dark",
  "Death Doom",
  "Death Gothic",
  "Death Grind",
  "Death Metal",
  "Death Thrash",
  "Death'n'Roll",
  "Deathcore",
  "Deathcore Thrash",
  "Doom Black",
  "Doom Metal",
  "Drone",
  "Electro Black",
  "Electro Metal",
  "Emo Metal",
  "Epic Black",
  "Experimental Metal",
  "Folk black",
  "Folk Death",
  "Folk Metal",
  "Funeral Doom",
  "Fusion",
  "Glam Rock",
  "Gothic Black",
  "Gothic Dark",
  "Gothic Death",
  "Gothic Doom",
  "Gothic Electro",
  "Gothic Metal",
  "Grind Death",
  "Grind Electro",
  "Grindcore",
  "Grunge",
  "Guitar Hero",
  "Hard FM",
  "Hard Rock",
  "Hardcore",
  "Heavy Death",
  "Heavy Metal",
  "Heavy Rock",
  "Indus Gothic",
  "Industrial Black",
  "Industrial Death",
  "Industrial Electro",
  "Industrial Metal",
  "Jazz Metal",
  "Melodic Black",
  "Melodic Black Death",
  "Melodic Death",
  "Melodic Death Black",
  "Melodic Doom",
  "Melodic Heavy",
  "Melodic Metal",
  "Melodic Power",
  "Metal",
  "Metalcore",
  "Modern Metal",
  "Neo Classical",
  "Noise Hardcore",
  "Nu Metal",
  "NWOBHM",
  "Pagan Black",
  "Pagan Folk",
  "Porno Gore Grind",
  "Post Hardcore",
  "Power Metal",
  "Progressive Black",
  "Progressive Death",
  "Progressive Heavy",
  "Progressive Metal",
  "Progressive Power",
  "Screamo",
  "Sludge Doom",
  "Sludge Metal",
  "Southern Rock",
  "Speed Heavy",
  "Speed Metal",
  "Stoner",
  "Stoner Doom",
  "Symphonic Black",
  "Symphonic Dark",
  "Symphonic Death",
  "Symphonic Death Black",
  "Symphonic Heavy",
  "Symphonic Metal",
  "Symphonic power",
  "Technical Death",
  "Technical Thrash",
  "Thrash Black",
  "Thrash Death",
  "Thrash Heavy",
  "Thrash Metal",
  "Thrash Neo",
  "Thrash Speed",
  "Unblack",
  "Viking Black",
  "Visual Kei"
];
export default genre;
